secrets:
  tektonBucket: ""
  featureFlagAPIKey: ""
  chartMuseum:
    username: ""
    password: ""
  pipelineUser:
    username: ""
    email: ""
    token: ""

serviceAccount:
  create: true
  name: jxl-boot
  annotations:
    foo: bar
    eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/jenkinsXaccessToS3

jxRequirements:
  cluster:
    clusterName: mycluster
    namespace: jx
    project: myproject
    provider: eks
    zone: europe-west1-c
