{{- if .Values.serviceAccount.create -}}
{{- $jx := .Values.jxRequirements -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jxl-boot
  # name: {{ include "jxl-boot.serviceAccountName" . }}
  labels:
    {{- include "jxl-boot.labels" . | nindent 4 }}
  annotations:
{{- if eq $jx.cluster.provider "gke" }}
    iam.gke.io/gcp-service-account: "{{ $jx.cluster.clusterName }}-jb@{{ $jx.cluster.project }}.iam.gserviceaccount.com"
{{- end }}
{{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | indent 4 }}
{{- end }}
{{- end -}}
