name: Kind
on: [push, pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Kind
      env:
        KIND_BDD_SECRETS: ${{ secrets.KIND_BDD_SECRETS }}
      run: |
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOBIN
        mkdir -p $GOBIN
        make build

        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x kubectl && mv kubectl $GOBIN
        wget https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind-linux-amd64 && mv kind-linux-amd64 $GOBIN/kind

     
        mkdir -p /tmp/kube
        export KUBECONFIG=/tmp/kube/config

        git clone https://github.com/jenkins-x-labs/cloud-resources.git
        echo "creating kind cluster"
        ./cloud-resources/kind/create_cluster.sh
        echo "kind cluster created; now connecting to it"

        kind get kubeconfig > $KUBECONFIG

        kubectl cluster-info
        kubectl wait --for=condition=Ready pods --all --namespace kube-system
        kubectl get pods -n kube-system
        
        echo "now lets import the secrets"
        
        echo $KIND_BDD_SECRETS > /tmp/secrets.yaml        
        ./build/jxl boot secrets import -git-url https://github.com/jstrachan/environment-kind-dev2 -f /tmp/secrets.yaml
        rm /tmp/secrets.yaml

        echo "now lets boot the cluster"

        ./build/jxl boot run -git-url https://github.com/jstrachan/environment-kind-dev2
